janpeterka/kucharka

- app/controllers/daily_plans.py
- app/controllers/event_exporter.py
- app/models/daily_plans.py
- app/models/ingredients.py
- app/models/shopping.py
- app/templates/event_exporter/_ingredient_list.html.j2
- app/templates/event_exporter/_ingredient_row.html.j2
- app/templates/event_exporter/_ingredient_table.html.j2
- app/templates/event_exporter/ingredient_list.html.j2
- app/templates/event_exporter/shopping_list.html.j2
- app/templates/events/_export.html.j2
> Fix shoppings amount

- app/controllers/daily_plans.py
- app/controllers/event_exporter.py
- app/controllers/forms/events.py
- app/models/daily_plans_have_recipes.py
- app/models/mixins/daily_plans/daily_plan_loaders.py
- app/models/mixins/daily_plans/daily_plan_recipes.py
- app/static/css/forms.css
- app/static/css/style.css
- app/templates/daily_plans/_recipe_row.html.j2
- app/templates/daily_plans/show.html.j2
- app/templates/event_exporter/_ingredient_list.html.j2
- app/templates/events/new.html.j2
- app/templates/recipes/show.html.j2
- migrations/versions/2021_07_02_add_portion_count.py
Přidává možnost úpravy počtu porcí u jednotlivých jídel v jídelníčku.
Defaultně se nastaví podle `event.people_count`, pak je možné změnit u jednotlivých jídel.
Nasazeno hlavně kvůli:
- mění se počet lidí na akci
- mám zvlášť vegetariánský recept pro část lidí a masový pro druhou část.
> Add portion count for every meal

- app/controllers/events.py
- app/models/events.py
- app/models/users.py
- app/static/css/details.css
- app/templates/events/_delete_or_edit.html.j2
- app/templates/events/_list.html.j2
- app/templates/events/index.html.j2
- app/templates/events/show.html.j2
- app/templates/macros/icons.html.j2
- migrations/versions/2021_07_12_event_archived.py
Přidává možnost archivovat akci. 
Closes #29
> Add archiving to event

- app/controllers/__init__.py
- app/controllers/admin_statistics.py
- app/static/css/admin.css
- app/templates/admin/_admin_notification_count.html.j2
- app/templates/navbars/_navbar_admin.html.j2
Přidává adminům upozornění na věci k vyřízení, aktuálně Tipy ke schválení.
Pro teď closes #32
> Add admin stat controller and admin notifications

- app/controllers/index.py
- app/controllers/public_recipes.py
- app/templates/index/index.html.j2
- app/templates/public_recipes/_recipe_row.html.j2
- app/templates/public_recipes/_recipes_table.html.j2
- app/templates/public_recipes/public_index.html.j2
Přidává veřejnou zjednodušenou stránku public recipes, aby se i neregistrovaní mohli podívat, co v aplikaci najdou.
Aktuálně nebude fungovat proklik do receptu, je to ještě ke zvážení, kam všude pustit neregistrované.
> Add public public recipes page

- app/controllers/__init__.py
- app/controllers/admin_statistics.py
- app/controllers/conversions.py
- app/controllers/ingredients.py
- app/models/__init__.py
- app/models/conversions.py
- app/models/ingredients.py
- app/templates/admin/index.html.j2
- app/templates/conversions/_add.html.j2
- app/templates/conversions/_conversion.html.j2
- app/templates/conversions/index.html.j2
- app/templates/dashboard/index.html.j2
- app/templates/ingredients/_edit_or_delete.html.j2
- app/templates/ingredients/show.html.j2
- app/templates/navbars/_navbar_admin.html.j2
- app/templates/recipes/show.html.j2
- kucharka.py
Přidává základní správu konverzí mezi mírami u dané suroviny.
Změny:
Stránka suroviny:
- zobrazení konverzí
- admin: přidání konverzí
Stránka receptu:
- zobrazení všech konverzí v info ikoně
Chybí:
- admin: upravit konverzi
- admin: smazat konverzi
> Add conversion management

- app/controllers/event_exporter.py
- app/static/css/print.css
- app/templates/event_exporter/cookbook.html.j2
- app/templates/recipes/_show_simple.html.j2
Pagination.
Zalamování stránek.
Schování "ze sdílených" v exportu.
Closes #55
> Improve exports

- app/models/recipes.py
> Duplicate category when duplicating recipe

- app/controllers/edit_recipes.py
- app/controllers/forms/ingredients.py
- app/controllers/forms/public_recipes.py
- app/controllers/forms/recipes.py
- app/controllers/ingredients.py
- app/controllers/public_recipes.py
- app/controllers/recipes.py
- app/helpers/base_mixin.py
- app/models/ingredients.py
- app/templates/macros/render_field.html.j2
Použití WTForms-SQLAlchemy pro jednodušší dynamické selecty napojené na databázi.
closes #10
> Add dynamic form select

- app/controllers/ingredients.py
- app/templates/ingredients/edit.html.j2
- app/templates/ingredients/new.html.j2
Řeší bug, při chybě se details otevírá.
closes #15
> Show errors on ingredient form (new, edit)

- app/controllers/fast_add_ingredients.py
- app/models/labels.py
- app/static/css/colors.css
- app/templates/macros/render_label.html.j2
- app/templates/recipes/_description.html.j2
- app/templates/recipes/_interactions.html.j2
- app/templates/recipes/_show.html.j2
- app/templates/recipes/_sidebar_details.html.j2
- app/templates/recipes/show.html.j2
- migrations/versions/202110021103_add_label_color.py
Lepší design zobrazení receptů, lepší zobrazení štítků.
closes #80
> Redesign recipe page details

- app/controllers/forms/public_recipes.py
- app/controllers/public_recipes.py
- app/models/ingredients.py
- app/templates/public_recipes/_recipe_row.html.j2
- app/templates/public_recipes/_recipes_table.html.j2
- app/templates/public_recipes/index.html.j2
- app/templates/recipes/index.html.j2
- jsou pryč seznamy surovin (divný a rozhazovalo to vizuál)
- lepší kód pro filtr surovin
closes #87
> Redesign public recipes

- app/controllers/event_exporter.py
- app/models/daily_plans.py
- app/models/events.py
- app/templates/daily_plans/show.html.j2
- app/templates/event_exporter/cookbook.html.j2
Zobrazit v exportech jenom recepty z aktivních dní.
Zobrazit varování, pokud se (přes url/historii) dostanu na neaktivní den.
closes #126
> Limit export to active daily plans, show warning.

- app/controllers/dashboard.py
- app/controllers/user_statistics.py
- app/helpers/item_mixin.py
- app/models/events.py
- app/models/users.py
- app/static/css/colors.css
- app/static/css/loader.css
- app/static/css/style.css
- app/templates/base/base.html.j2
- app/templates/dashboard/_current.html.j2
- app/templates/dashboard/_tasks.html.j2
- app/templates/dashboard/index.html.j2
- app/templates/ingredients/_ingredients_without_category.html.j2
- app/templates/ingredients/_ingredients_without_measurement.html.j2
- app/templates/ingredients/_recipes_with_zero_amount_ingredient.html.j2
- app/templates/macros/loader.html.j2
- app/templates/recipes/_draft_recipes.html.j2
- app/templates/recipes/_recipes_without_category.html.j2
- app/templates/recipes/edit/_edit_ingredient.html.j2
- kucharka.py
- Redesign
- loader
- zjednodušený loadování tasků
> Improve dashboard layout

- app/templates/javascript/_select_badges_controller.js
- app/templates/public_recipes/index.html.j2
> Don't add badges if they already exist

- app/controllers/recipes.py
- app/models/recipes.py
- app/templates/javascript/_select_badges_controller.js
- app/templates/recipes/_interactions.html.j2
- zkopírovaný recept má na konci jména "(kopie)"
- zkopírovaný recept má labely.
- zkopírovaný vlastní recept otevírá rovnou editaci
- smazání receptu se snaží přesměrovat na poslední rozumnou stránku
closes #128
> Rename duplicated recipe

- app/static/css/atomic.css
- app/templates/ingredient_categories/_ingredient_category.html.j2
- app/templates/macros/icons.html.j2
- app/templates/measurements/_error.html.j2
- app/templates/measurements/_measurement.html.j2
- app/templates/navbars/navbar.html.j2
- app/templates/recipe_categories/_recipe_category.html.j2
- move profile to right, group logout under that
- move Tips under new 'more' (...) dropdown
- fix collapsed navbar not working due to new naming convention
> Move profile in navbar

- .github/workflows/test.yaml
- Pipfile
- Pipfile.lock
- app/__init__.py
- app/controllers/index.py
- app/controllers/public_recipes.py
- app/models/roles.py
- app/models/users.py
- config.py
- kucharka.py
- mypy.ini
- pytest.ini
- tests/__init__.py
- tests/conftest.py
- tests/helpers.py
- tests/unit/test_base.py
Konečně přidávám základní testy (že stránky reagují) a hlavně celý kód kolem testování.
Bude tedy možné přidat další důležité unit testy.
> Add basic unit tests

- app/models/users.py
- tests/conftest.py
- tests/data_helpers.py
- tests/helpers.py
- tests/unit/test_base.py
Admin and application_manager roles tests.
> Add tests with roles

- app/controllers/__init__.py
- app/controllers/admin.py
- app/models/recipes.py
- app/models/users.py
- app/static/css/admin.css
- app/templates/admin/_admin_warning.html.j2
- app/templates/admin/_env_badge.html.j2
- app/templates/base/base.html.j2
- app/templates/navbars/_navbar_admin.html.j2
Zobrazení toho, jestli je člověk přihlášený jako admin, a možnost dočasně přestat nahlížet na stránku jako admin.
> Add admin toggle

- app/static/css/atomic.css
- app/templates/macros/render_image.html.j2
- app/templates/recipes/show.html.j2
> Allow centering render_image, center cover photo

- app/controllers/__init__.py
- app/controllers/user_calendars.py
- app/controllers/users.py
- app/templates/javascript/_clipboard_controller.js
- app/templates/javascript/stimulus.js.html
- app/templates/users/show.html.j2
- ical byl za loginem
- přidal jsem button na vkládání url do clipboardu
> Fix hidden ical

- app/controllers/edit_recipes.py
- app/controllers/forms/recipes.py
- app/controllers/recipes.py
- app/helpers/base_mixin.py
- app/templates/recipes/_interactions.html.j2
> Refactor recipe form label handling

- app/controllers/events/edit_events.py
- app/templates/events/_more_options.html.j2
- app/templates/events/_sharing.html.j2
Sharing options were shown event, sharing (and unsharing) was enabled for `edit`permissions
> Improve event sharing options

- app/controllers/edit_recipes.py
- app/helpers/base_mixin.py
- app/templates/recipes/edit.html.j2
- app/templates/recipes/edit/_ingredient_table.html.j2
Because when portion_count changes, ingredient info didn't
> Reload ingredient table when recipe changed

- kucharka.py
Enable/disable FF by setting ?ff_name=1/0 in URL
> Enable setting FF by request arg

- app/controllers/forms/events.py
Nastavovalo se v čase re/startu aplikace. Teď se nastavuje v moment vytvoření.
> Set default date values on form creation instead of on app start

- app/templates/javascript/_select_badges_controller.js
- app/templates/public_recipes/index.html.j2
bylo špatně pořadí podmínek a padalo to na tom.
> Fix select badges on public recipes

- app/templates/daily_plans/_edit_recipe_row.html.j2
- app/templates/daily_plans/_recipe_row.html.j2
Button měl černý text na tmavém pozadí, not great. Changed
> Change button text color to improve readability

- app/__init__.py
- kucharka.py
- trace all transactions
- see user info
> Increase Sentry monitoring

- Pipfile
- Pipfile.lock
- app/controllers/support.py
Add gevent to support websocket correctly
> Add gevent

- app/controllers/public_recipes.py
- app/models/__init__.py
- app/static/css/atomic.css
- app/templates/base/base.html.j2
- app/templates/macros/render_field.html.j2
- app/templates/macros/turbo.html.j2
- app/templates/public_recipes/_recipe_card.html.j2
- app/templates/public_recipes/_recipes_cards.html.j2
- app/templates/public_recipes/card_index.html.j2
- app/templates/public_recipes/index.html.j2
- kucharka.py
> Add recipe index with cards and some other improvements

- app/controllers/events/share_events.py
- app/controllers/tips.py
- app/models/events.py
- app/models/tips.py
- app/services/__init__.py
- app/services/events/role_manager.py
- app/services/role_manager.py
- app/services/tips/approver.py
Adds structure for services, moves some code to services
> Add services

- app/controllers/events/events.py
- app/controllers/recipe_tasks.py
- app/helpers/context_processors.py
- app/helpers/formaters.py
- app/helpers/general.py
- app/models/__init__.py
- app/models/daily_plans.py
- app/models/event_days.py
- app/models/events.py
- app/models/mixins/daily_plans/daily_plan_loaders.py
- app/models/mixins/day_mixin.py
- app/services/__init__.py
- app/services/events/timetable_contructor.py
- app/templates/daily_plans/_day_badge.html.j2
- app/templates/daily_plans/_tasks.html.j2
- app/templates/events/edit.html.j2
- app/templates/events/show.html.j2
- kucharka.py
Refactor and move Event Timetable creation, also fixing tasks not shown in inactive days and in days that weren't show before
closes #345
> Show tasks in days before event

- app/models/ingredients.py
- app/services/daily_plans/ingredient_calculator.py
Page was totally broken by upgrade to SQLAlchemy 2.x
There was also bug with wrong path
> Correctly load export pages in SQLAlchemy 2.x

- app/__init__.py
- app/modules/auth/passwordless.py
- app/static/js/controllers/passwordless_controller.js
- app/static/js/src/app.js
- app/static/package-lock.json
- app/static/package.json
- app/templates/users/show.html.j2
- config.py
Add link passwordless for playing
> Add passwordless

- app/controllers/support.py
- app/modules/auth/passwordless.py
- app/static/js/controllers/passwordless_controller.js
- app/templates/base/_flash.html.j2
- app/templates/support/passwordless.html.j2
Add testing site "support/passwordless" for further playing with passwordless
> Add passwordless registration

- app/templates/macros/render_label.html.j2
- app/templates/recipes/_sidebar_details.html.j2
- app/templates/recipes/_tasks.html.j2
- app/templates/recipes/show.html.j2
Přeuspořádání stránky receptu.
Oprava linku na úpravu úkolu, aby vyskočil z turbo-frame
> Improve recipe page, fix wrong turbo frame

- app/controllers/attendance.py
- app/controllers/attendees.py
- app/forms/attendees.py
- app/helpers/context_processors.py
- app/helpers/general.py
- app/models/events.py
- app/models/portion_types.py
- app/static/css/colors.css
- app/static/js/controllers/class_change_controller.js
- app/static/js/controllers/form_controller.js
- app/static/js/controllers/select_badges_controller.js
- app/static/js/controllers/sortable_controller.js
- app/templates/attendances/_form_fields.html.j2
- app/templates/attendances/_new_form.html.j2
- app/templates/attendances/_row.html.j2
- app/templates/attendances/export.html.j2
- app/templates/attendances/index.html.j2
- app/templates/components/buttons/button_to.html.j2
- app/templates/daily_plans/_recipe_row.html.j2
- app/templates/macros/turbo.html.j2
- app/templates/portion_types/_portion_count_form.html.j2
- app/templates/portion_types/index.html.j2
- app/templates/portion_types/new.html.j2
- app/templates/recipes/edit/ingredient/_row.html.j2
- app/templates/tips/_tip.html.j2
- kucharka.py
Předělání přehledu strávníků:
- Správa skupin je jasnější
- Editace je "live update"
> Polish attendance index

- app/models/recipe_tasks.py
- app/models/recipes.py
- tests/factories/__init__.py
- tests/factories/recipe_tasks.py
- tests/unit/recipes/test_recipes.py
> Duplicate tasks on recipe duplication

- app/models/concerns/events/attendable.py
- app/templates/attendances/_form_fields.html.j2
- app/templates/attendances/_row.html.j2
- tests/end_to_end/test_public_recipes_flow.py
Add missing cascade on attendances, which stopped from deleting event
> Correct cascade from event to attendees

- app/controllers/__init__.py
- app/controllers/events/event_duplications.py
- app/controllers/events/events.py
- app/models/daily_plans.py
- app/models/events.py
- app/presenters/events.py
- app/templates/event_duplications/new.html.j2
- app/templates/events/_other_options.html.j2
- app/templates/events/new.html.j2
Přidává mezikrok při duplikování události.
Ten umožňuje nastavit nový název, počet lidí, a hlavně změnit datum kdy akce začíná.
Tím se vytvoří data ve správném novém intervalu, a v nich jsou spárvně recepty.
> Enhance event duplication
